--- 
- hosts: 172.31.36.138 
  become: yes 
  tasks:
  - include_tasks: files.yml
  - name: create a folder
    file: 
     path: /home/ubuntu/myfolder
     state: directory
  - name: i want to copy file 
    copy:
     src: staticfile
     dest: /home/ubuntu/staticfile.txt 

  - name: install apache2
    apt:
     name: apache2
     state: present 

  - name: copy dynamic file 
    template: 
     src: myindex.j2
     dest: /var/www/html/index.html