--- 
- hosts: 172.31.36.138 
  become: yes 
  tasks:
  - include_tasks: files.yml
  - name: create a folder
    file: 
     path: /home/ubuntu/myfolder
     state: directory
  - name: i want to copy file 
    copy:
     src: staticfile
     dest: /home/ubuntu/staticfile.txt 
