--- 
- hosts: 172.31.36.138
  become: yes
  tasks: 
  - include_tasks: filee.yml
  - name: create a folder 
    file: 
     path: /home/ubuntu/folderf1
     state: directory 
  - name: i want to my share file 
    copy: 
     src: chin2
     dest: /home/ubuntu/yatish1.txt
  - name: install apache 
    apt: 
     name: apache2 
     state: present 
  - name: copy dyanamic table 
    template: 
     src: yadav
     dest: /var/www/html/index.html 
  - name: download 
    get_url:
    url: https://get.jenkins.io/war/2.370/jenkins.war
    dest: jenkins.war
    force_basic_auth: yes