--- 
- hosts: 172.31.36.138
  become: yes
  tasks: 
  - include_tasks: filee.yml
  - name: create a folder 
    file: 
     path: /home/ubuntu/folderf1
     state: directory 
  - name: i want to copy files 
    copy: 
     src: chin2
     dest: /home/ubuntu/yatish1.txt
