--- 
- hosts: 172.31.36.138 
  become: yes 
  tasks :
  - include_tasks: filee.yml 
  - name: create a folders 
    file: 
     path: /home/ubuntu/myfolders 
     state: directory 
  - name: i want to copy files 
    copy: 
     src: ystaticfile
     dest: /home/ubuntu/ystaticfile.txt
  - name: install apache2 
    apt: 
     name: apache2 
     state: present 
  - name: copy dynamic files 
    template: 
     src: Iindexj2
     dest: /var/www/html/index.html 
  - name: download internet files 
    get_url:
     url: https://get.jenkins.io/war-stable/2.361.1/jenkins.war
     dest: /home/ubuntu/jenkins.war
     force_basic_auth: yes

  