--- 
- hosts: 172.31.36.138 
  become: yes 
  tasks :
  - include_tasks: filee.yml 
  - name: create a folders 
    file: 
     path: /home/ubuntu/myfolders 
     state: directory 
  - name: i want to copy files 
    copy: 
     src: ystaticfile
     dest: /home/ubuntu/ystaticfile.txt

  