--- 
- hosts: 172.31.36.138  
  become: yes 
  tasks: 
  - include_tasks: myfile.yml 
  - name: create a folder 
    file: 
      path: /home/ubuntu/myfolder 
      state: directory 
  - name: i want to copy files 
    copy:   
      src: ystaticfile
      dest: /home/ubuntu/mystaticfile.txt    