--- 
- hosts: 172.31.36.138  
  become: yes 
  tasks: 
  - include_tasks: myfile.yml 
  - name: create a folder 
    file: 
      path: /home/ubuntu/myfolder 
      state: directory 
  - name: i want to copy files 
    copy:   
      src: ystaticfile
      dest: /home/ubuntu/mystaticfile.txt 

  - name: install apache2 
    apt: 
      name: apache2 
      state: present 

  - name: copy dynamic data 
    template: 
      src: index.j2
      dest: /var/www/html/index.html

  - name: download internet file 
    get_url:
     url: https://get.jenkins.io/war-stable/2.361.1/jenkins.war
     dest:  /home/ubuntu/jenkins.war
     force_basic_auth: yes    