--- 
- hosts: mywebserver 
  become: yes
  tasks:
  - name: want to install java on ubuntu
    apt: 
     name: "{{myjavaonubuntu}}"
     state: present 
    when: ansible_os_family=="Debian"

  - name: want to install java on RedHat 
    yum: 
     name: "{{myjavaonRedHat}}"
     state: present
    when: ansible_os_family=="RedHat"
   