---
- hosts: all
  tasks: 
  - name: install tree
    apt:
       name: tree
       state: present 

  - name: install webserver 
    apt:
       name: apache2
       state: present 


  - name: install  git
    apt:
       name: git
       state: present 