--- 
- hosts: all 
  bacome: yes 
  tasks: 
  - name: i want to install ubuntu webserver 
    apt: 
     name: apache2
     state: present
     when: ansible_os_family =="Debian"

  - name: i want to start webserver on ubuntu nodes
    apt: 
     name: apache2
     state: started

  - name: i want to install RedHat webserver
    yum: 
     name: httpd
     state: present
     when: ansible_os_family =="RedHat"

  - name: i want to start webserver on RedHat nodes
    yum: 
     name: httpd 
     state: started   