--- 
- hosts: prject01 
  become: yes 
  tasks: 
  - name: i want to install ubuntu webserver
    apt: 
      name: apache2
      state: present 
    when: ansible_os_family =="Debian"  

  - name: i want to start webserver on ubuntu nodes
    service: 
      name: apache2 
      state: started 
    when: ansible_os_family =="Debian" 

  - name: i want to install RedHat webserver 
    yum: 
      name: "{{myserverbackonRedHat}}"
      state: present 
    when: ansible_os_family =="RedHat" 

  - name: i want to start webserver on RedHat nodes 
    service: 
     name: "{{myserverbackonRedHat}}" 
     state: started 
    when: ansible_os_family =="RedHat"