--- 
- hosts: all
  become: yes 
  tasks: 
  - name: i want to install ubuntu webserver
    apt: 
      name: apache2
      state: present
    when: ansible_os_family=="Debain"

  - name: i want to start webserver on ubuntu
    service:
     name: apache2
     state: started

  - name: i want to install RedHat webserver
    yum: 
      name: httpd 
      state: present
    when: ansible_os_family=="RedHat"    

  - name: i want to start webserver on RedHat nodes
    service:
     name: apache2
     state: started

